// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsqMBACkzjr9CTnv8E5tkH7VtFRWfAfWo',
    appId: '1:566650330933:web:790a974faa9ab2aa91767c',
    messagingSenderId: '566650330933',
    projectId: 'njrdevs-attendance',
    authDomain: 'njrdevs-attendance.firebaseapp.com',
    storageBucket: 'njrdevs-attendance.appspot.com',
    measurementId: 'G-MVEQDJCTGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjQdr18FHUBn4LYEnLDlOMbPqWGnMjo8g',
    appId: '1:566650330933:android:1612e34001a369dd91767c',
    messagingSenderId: '566650330933',
    projectId: 'njrdevs-attendance',
    storageBucket: 'njrdevs-attendance.appspot.com',
  );
}
